version: '3.8'

services:

  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  postgresql:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"